// <auto-generated />
using System;
using AY.SmartEngine.Infrastructure.Repositories.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AY.SmartEngine.Infrastructure.TaskQueue.Migrations.SQLite.Migrations
{
    [DbContext(typeof(TaskQueueDbContext))]
    [Migration("20260413082616_SetTaskQueueIndex")]
    partial class SetTaskQueueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AY.SmartEngine.Domain.TaskQueue.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("ParentJobId")
                        .HasDatabaseName("idx_jobs_parent");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("idx_jobs_scheduled");

                    b.HasIndex("QueueName", "JobStatus")
                        .HasDatabaseName("idx_jobs_queue_status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("AY.SmartEngine.Domain.TaskQueue.Entities.JobHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("idx_Jobhistory_jobid");

                    b.ToTable("JobHistories");
                });

            modelBuilder.Entity("AY.SmartEngine.Domain.TaskQueue.Entities.JobQueueEntity", b =>
                {
                    b.Property<Guid>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("QueueId");

                    b.HasIndex("QueueName")
                        .IsUnique()
                        .HasDatabaseName("idx_jobqueues_name");

                    b.ToTable("JobQueues");
                });

            modelBuilder.Entity("AY.SmartEngine.Domain.TaskQueue.Entities.JobEntity", b =>
                {
                    b.HasOne("AY.SmartEngine.Domain.TaskQueue.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
